# Generated by Django 5.2.5 on 2025-12-18 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_questionpaper_question_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='category',
            field=models.CharField(blank=True, choices=[('JCOs (All tdes less Dvr MT,DR,EFS,Lmn and Tdn)', 'JCOs (All tdes less Dvr MT,DR,EFS,Lmn and Tdn)'), ('OR (All tdes less Dvr MT,DR,EFS,Lmn and Tdn)', 'OR (All tdes less Dvr MT,DR,EFS,Lmn and Tdn)'), ('JCOs/OR (Dvr MT,DR,EFS,Lmn and Tdn)', 'JCOs/OR (Dvr MT,DR,EFS,Lmn and Tdn)')], help_text='Category this paper belongs to', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='exam_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=10800), null=True),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='question_paper',
            field=models.CharField(choices=[('Primary', 'Primary')], default='Primary', max_length=20),
        ),
    ]
