# Generated by Django 5.2.5 on 2025-12-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_add_category_and_upload_to_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionupload',
            name='trade',
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, choices=[('JCOs (All tdes less Dvr MT,DR,EFS,Lmn and Tdn)', 'JCOs (All tdes less Dvr MT,DR,EFS,Lmn and Tdn)'), ('OR (All tdes less Dvr MT,DR,EFS,Lmn and Tdn)', 'OR (All tdes less Dvr MT,DR,EFS,Lmn and Tdn)'), ('JCOs/OR (Dvr MT,DR,EFS,Lmn and Tdn)', 'JCOs/OR (Dvr MT,DR,EFS,Lmn and Tdn)')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='question_paper',
            field=models.CharField(choices=[('IT Trophy', 'IT Trophy')], default='IT Trophy', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionupload',
            name='category',
            field=models.CharField(blank=True, choices=[('JCOs (All tdes less Dvr MT,DR,EFS,Lmn and Tdn)', 'JCOs (All tdes less Dvr MT,DR,EFS,Lmn and Tdn)'), ('OR (All tdes less Dvr MT,DR,EFS,Lmn and Tdn)', 'OR (All tdes less Dvr MT,DR,EFS,Lmn and Tdn)'), ('JCOs/OR (Dvr MT,DR,EFS,Lmn and Tdn)', 'JCOs/OR (Dvr MT,DR,EFS,Lmn and Tdn)')], help_text='Select the candidate category this upload belongs to.', max_length=255, null=True),
        ),
    ]
