# Generated by Django 5.2.5 on 2025-12-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_candidateprofile_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='secondary_credits',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='secondary_duration',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='secondary_practical_marks',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='secondary_qualification',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='secondary_viva_marks',
        ),
    ]
