"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1hh)2)lf-ld%vd7)f84o-6t5f*4e36u_sn#2i)5)w(d2b!9+(d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "import_export",
    "django_filters",
    "accounts",
    "reference.apps.ReferenceConfig",
    "centers",
    "registration",
    "questions.apps.QuestionsConfig",
    "exams",
    "results",
    "syncops",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'it_trophy_1',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',   # or '127.0.0.1' or remote host
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

AUTH_USER_MODEL = "accounts.User"

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True
USE_TZ = True

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "candidate_dashboard"
LOGOUT_REDIRECT_URL = "login"
LOGIN_URL = "login"



from mongoengine import connect

connect(
    db="examportal",
    host="mongodb://localhost:27017/examportal"  # or your MongoDB Atlas URI
)


STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "config" / "static",   # since your static is inside config/
]


JAZZMIN_SETTINGS = {
    "site_title": "2 STC Online Exam Portal",
    "site_header": "2 STC",
    "site_brand": "2 STC Portal",
    "welcome_sign": "JAI HIND! Welcome to 2STC Online Exam Portal",
    "copyright": "Developed by SLOG Solutions Pvt Ltd and 2STC",
    
    # Logo settings
    "site_logo": "img/logo.png",
    "login_logo": "img/logo.png",
    "login_logo_dark": "img/logo.png",
    
    # Icons configuration
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "exams.Exam": "fas fa-file-alt",
        "exams.Question": "fas fa-question-circle",
        "exams.Result": "fas fa-chart-line",
        "students.Student": "fas fa-user-graduate",
    },
    
    # Top menu links
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "https://www.slogsolutions.com", "new_window": True},
    ],
    
    # UI tweaks
    "show_ui_builder": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "centers",
        "exams",
        "questions",
        "registration",
        "users"   # <= Users section will be here, below Registration
    ],

    
    # # Order apps
    # # "order_with_respect_to": ["auth", "exams", "students"],
    
    # # Custom links
    # "custom_links": {
    #     "exams": [{
    #         "name": "Generate Reports", 
    #         "url": "generate_reports", 
    #         "icon": "fas fa-chart-pie",
    #         "permissions": ["exams.view_result"]
    #     }]
    # },
    

    
    # Show sidebar
    "show_sidebar": True,
    
    # Language
    "language_chooser": False,
    "custom_css": "css/admin-overrides.css",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "cyborg",
    "dark_mode_theme": None,
    "navbar": "navbar-dark navbar-primary",
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "accent": "accent-primary",
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}


# settings.py
CONVERTER_PASSPHRASE = os.environ.get("CONVERTER_PASSPHRASE", "bharat")
DATA_UPLOAD_MAX_NUMBER_FIELDS=100000
    